MAIN_MENU_BG_COLOR = "#9f9794"
MAIN_MENU_BUTTONS_BG_COLOR = "#edece7"
MAIN_MENU_TEXT_COLOR = "#9e3e32"

MAIN_MENU_TITLE_TEXT_FONT = "Helvetica 32 bold"
MAIN_MENU_BUTTONS_TEXT_FONT = "Helvetica 20 bold"

WINDOW_MIN_SIZES = (1000, 700)
WINDOW_DEFAULT_SIZES = "1200x700"
WINDOW_TITLE = "Data Project"
